defmodule InvoiceGoblin.Repo.Migrations.AddIsPlaceholderToOrganisations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:statements) do
      modify :title, :text, null: true
    end

    alter table(:organisations) do
      add :is_placeholder, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:organisations) do
      remove :is_placeholder
    end

    alter table(:statements) do
      modify :title, :text, null: false
    end
  end
end
