defmodule InvoiceGoblin.Repo.Migrations.AddWaitlist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:waitlist, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:waitlist, [:email], name: "waitlist_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:waitlist, [:email], name: "waitlist_unique_email_index")

    drop table(:waitlist)
  end
end
